version: '3.8'

services:
  buryatvpn:
    build: .
    container_name: buryatvpn_app
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - DATABASE_URL=postgresql://buryatvpn:password@postgres:5432/buryatvpn
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - buryatvpn-network

  postgres:
    image: postgres:15-alpine
    container_name: buryatvpn_postgres
    environment:
      POSTGRES_DB: buryatvpn
      POSTGRES_USER: buryatvpn
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - buryatvpn-network

  redis:
    image: redis:7-alpine
    container_name: buryatvpn_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - buryatvpn-network

  prometheus:
    image: prom/prometheus:latest
    container_name: buryatvpn_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - buryatvpn-network

  grafana:
    image: grafana/grafana:latest
    container_name: buryatvpn_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - buryatvpn-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  buryatvpn-network:
    driver: bridge
